# Exploring the Clustering of Chicken Calls via Numeric Data
After generating clusters of chicken calls by their acousting features, this program takes that output and generates a table for sme of hte more human-readable measures like duration and peak frequency and generates tables of means and standard deviations by cluster. 

The program k_means_cluster_adult_chicken_calls.ipynb found 8 clusters with between 29-227 calls each.

Steps:
1. Download the data and separate into different data frames for each cluster
2. Set up a function that takes in a data frame and randomly selects a certain number of rows from that dataframe (e.g., 10 rows). Each row has 1 call. For each row, it downloads the associated audio file, prints a 2-second spectrogram with the call outlined in the middle.
3. Run this function for each cluster
4. Compare visually the spectrograms for each cluster. Do they look more similar to each other than to the spectrograms of other clusters?


Author: K Rubio

Last modified: 12Aug26

In [9]:
import os
import sys
from pathlib import Path
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
# have to modify where notebook looks for imports so it looks in the project root, not the notebook folder
os.getcwd()
sys.path.append(str(Path().resolve().parent.parent))
print(sys.path)

['/Users/dontfreakout/.pyenv/versions/3.12.8/lib/python312.zip', '/Users/dontfreakout/.pyenv/versions/3.12.8/lib/python3.12', '/Users/dontfreakout/.pyenv/versions/3.12.8/lib/python3.12/lib-dynload', '', '/Users/dontfreakout/Documents/Education (reduced)/Computer_Science/ML_and_Data_Science/Audio Signal Processing/Completed Projects/2026_04_Audio_Signal_Analysis/audio-signal-analysis/.venv/lib/python3.12/site-packages', '/Users/dontfreakout/Documents/Education (reduced)/Computer_Science/ML_and_Data_Science/Audio Signal Processing/Completed Projects/2026_04_Audio_Signal_Analysis/audio-signal-analysis']

In [3]:
# import the data
filename = '2026-07-31_cluster_adult_analysis_output'
df = pd.read_csv(f"../../data/output/chickens/{filename}.csv")

In [4]:
columns_to_keep = [
  'duration_ms',
  'time_to_next_call_ms',
  'min_freq',
  'max_freq',
  'max_energy_freq',
  'freq_change',
  'slope',
  'zcr',
  'spectral_centroid',
  'spectral_bandwidth',
  'cluster',
]

df = df[columns_to_keep]
df

,duration_ms,time_to_next_call_ms,min_freq,max_freq,max_energy_freq,freq_change,slope,zcr,spectral_centroid,spectral_bandwidth,cluster
0,122,36.000000,1205.859375,1421.191406,1335.058594,86.132812,353.003330,0.124467,2905.300460,2624.356786,1
1,700,302.000000,1033.593750,1378.125000,1119.726563,215.332031,-307.617188,0.113120,1871.231320,1644.881799,2
2,600,416.000000,1076.660156,1248.925781,1119.726563,0.000000,0.000000,0.104755,1723.434437,1378.180724,2
3,484,354.000000,689.062500,1076.660156,1033.593750,301.464844,-622.861247,0.083729,1400.304624,1286.143802,2
4,530,222.222222,1033.593750,1335.058594,1119.726563,43.066406,0.000000,0.100480,1801.598218,1627.250258,2
...,...,...,...,...,...,...,...,...,...,...,...
813,122,122.000000,172.265625,1076.660156,215.332031,0.000000,0.000000,0.065607,1653.708501,2150.898274,7
814,336,90.000000,129.199219,1076.660156,387.597656,129.199219,384.521484,0.055428,1728.824871,2263.841987,7
815,142,38.000000,129.199219,818.261719,258.398438,43.066406,303.284551,0.052969,1970.696584,2664.557015,7
816,504,26.000000,172.265625,645.996094,258.398438,0.000000,0.000000,0.049187,1864.329548,2631.823427,7
817,220,32.000000,172.265625,387.597656,258.398438,0.000000,0.000000,0.036287,1560.531716,2454.517792,7

In [10]:

for col in columns_to_keep:
  df_meta = df.groupby("cluster")[col].agg(
      num_of_files="count",
      mean_duration="mean",
      max_duration="max",
      min_duration="min",
      std_duration="std"
  ).reset_index()
  print(f"\n{col}")
  display(df_meta)

duration_ms

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,88.879433,788,26,139.629585
1,1,29,90.275862,418,26,107.008310
2,2,69,629.043478,2298,88,479.929726
3,3,72,193.222222,1328,28,258.307722
4,4,34,116.588235,1040,32,198.051435
5,5,111,241.405405,1316,32,209.470952
6,6,135,250.948148,998,54,225.391180
7,7,227,150.431718,1220,26,219.979179

time_to_next_call_ms

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,258.806495,3617.333333,24.0,433.657001
1,1,29,291.048515,2044.000000,26.0,468.114542
2,2,69,1180.088624,8014.000000,24.0,1673.878962
3,3,72,205.587897,2181.666667,28.0,334.614394
4,4,34,308.153705,770.000000,36.0,145.529570
5,5,111,208.847659,2936.000000,24.0,381.983760
6,6,135,196.772115,1882.000000,34.0,219.849424
7,7,227,135.348820,1160.000000,24.0,169.101280

min_freq

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,476.173953,1033.593750,129.199219,239.881542
1,1,29,273.248922,1205.859375,86.132812,269.263671
2,2,69,735.249660,1291.992188,172.265625,266.025052
3,3,72,341.540527,861.328125,129.199219,165.036236
4,4,34,210.265395,387.597656,129.199219,55.865437
5,5,111,595.169975,861.328125,172.265625,147.618286
6,6,135,482.024740,1033.593750,172.265625,141.324769
7,7,227,237.908694,645.996094,129.199219,100.004141

max_freq

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,1442.266456,2799.316406,947.460938,399.202822
1,1,29,3093.356008,10465.136720,430.664062,2871.989855
2,2,69,1433.674423,3617.578125,947.460938,603.793177
3,3,72,1405.041504,2928.515625,732.128906,412.663241
4,4,34,889.194623,1076.660156,645.996094,119.895248
5,5,111,965.308277,1550.390625,689.062500,170.639877
6,6,135,1897.154948,4263.574219,1119.726563,650.508063
7,7,227,1204.531336,3359.179688,387.597656,341.766385

max_energy_freq

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,1017.711104,1894.921875,645.996094,158.521431
1,1,29,660.846579,1335.058594,172.265625,359.265560
2,2,69,999.889606,1335.058594,732.128906,134.752310
3,3,72,769.812012,1291.992188,215.332031,208.106358
4,4,34,592.796415,861.328125,258.398438,156.560966
5,5,111,771.315456,1335.058594,516.796875,124.486845
6,6,135,1058.795573,1378.125000,473.730469,207.100397
7,7,227,550.756728,990.527344,172.265625,195.555661

freq_change

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,177.763464,904.394531,0.0,203.101507
1,1,29,494.521148,1808.789063,0.0,453.239135
2,2,69,280.867867,2627.050781,0.0,444.354912
3,3,72,337.951660,1119.726563,0.0,272.247296
4,4,34,236.865234,689.062500,0.0,196.713260
5,5,111,143.166702,645.996094,0.0,142.736173
6,6,135,258.398438,3789.843750,0.0,383.505096
7,7,227,190.289011,947.460938,0.0,194.364225

slope

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,219.294480,16999.897200,-17944.335940,4779.974786
1,1,29,-5879.018734,10766.601560,-49795.532230,12766.657353
2,2,69,393.654868,6909.049131,-1511.101974,1534.836544
3,3,72,-227.941570,13251.201920,-22729.492190,5780.937663
4,4,34,-2232.284531,3799.977022,-20187.377930,6264.375083
5,5,111,491.847083,9110.201322,-20187.377930,2399.822051
6,6,135,594.578919,16195.913460,-4486.083984,2031.610926
7,7,227,-154.219251,18841.552730,-18662.109370,4539.977959

zcr

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,0.083438,0.153252,0.049805,0.012872
1,1,29,0.148136,0.347517,0.041748,0.063138
2,2,69,0.104684,0.190376,0.070679,0.023785
3,3,72,0.077174,0.142653,0.040737,0.017909
4,4,34,0.047520,0.079316,0.034180,0.008857
5,5,111,0.069332,0.098940,0.050846,0.009064
6,6,135,0.108063,0.251572,0.068537,0.022486
7,7,227,0.058913,0.100911,0.031467,0.012983

spectral_centroid

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,1690.599830,2744.755942,1004.153310,272.508507
1,1,29,3029.907673,4803.117120,1952.140638,682.249981
2,2,69,1744.434662,2594.701691,1278.948934,305.737723
3,3,72,1638.616359,2488.665627,1021.783736,328.063639
4,4,34,932.035663,1324.568512,676.494108,204.715149
5,5,111,1402.917827,2244.317487,958.422807,247.286726
6,6,135,1969.606526,3538.551327,1337.448103,374.571912
7,7,227,1416.955254,2326.685156,893.623453,285.519531

spectral_bandwidth

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,1749.815079,2580.868800,1096.858080,297.876490
1,1,29,2738.042558,3240.731678,1816.859606,295.470580
2,2,69,1569.181140,2346.863587,1030.573620,275.360171
3,3,72,1808.534968,2581.432798,1164.887752,318.395249
4,4,34,1208.635159,1747.732345,828.798757,290.748673
5,5,111,1604.112132,2528.846376,980.676305,284.122040
6,6,135,1815.934502,2680.453207,1211.017717,291.869371
7,7,227,1766.510998,2664.557015,1077.937136,331.203124

cluster

,cluster,num_of_files,mean_duration,max_duration,min_duration,std_duration
0,0,141,0.0,0,0,0.0
1,1,29,1.0,1,1,0.0
2,2,69,2.0,2,2,0.0
3,3,72,3.0,3,3,0.0
4,4,34,4.0,4,4,0.0
5,5,111,5.0,5,5,0.0
6,6,135,6.0,6,6,0.0
7,7,227,7.0,7,7,0.0